import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "About", description: "Meet DevTork Studio—clear thinking, thoughtful design, responsible technology, and a focused delivery process." };

export default function AboutPage() {
  return (
    <>
      <section className="page-hero page-hero-animated section-dark no-cream-nav"><div className="container parallax-layer" data-parallax data-parallax-speed="0.035"><p className="eyebrow">About us</p><h1 className="page-title">Small enough to care. Serious enough to deliver.</h1><p className="lead muted">DevTork is a digital studio for teams that value clear thinking, thoughtful design, and technology that keeps working after launch.</p></div></section>
      <section className="section"><div className="container"><p className="manifesto" data-reveal>We are here to make digital work feel <span className="muted-word">less confusing, less generic,</span> and much more useful.</p></div></section>
      <section className="section section-paper-2"><div className="container"><div className="section-head"><div><p className="eyebrow">How we work</p><h2>Four things we protect.</h2></div></div><div className="value-grid" data-stagger>{[["01", "Clarity", "Clients should understand the plan. Users should understand the interface. Our job is to reduce uncertainty on both sides."], ["02", "Originality", "We learn from great work but do not copy it. Every visual and interaction needs a reason that belongs to the project."], ["03", "Responsibility", "Security, accessibility, performance, privacy, and honest communication are part of quality—not details to add later."], ["04", "Momentum", "We show progress in useful form, make decisions visible, and keep projects moving without unnecessary meetings or mystery."]].map(([no, title, text]) => <article className="value-card" key={no}><span>{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="section"><div className="container"><div className="split-heading studio-team-grid"><div><p className="eyebrow">A flexible senior team</p><h2>Built around the work.</h2></div><div className="studio-team-copy"><p className="copy-lg muted">We bring together strategy, design, development, content, and growth skills based on what the project actually needs. That keeps communication direct and the team focused.</p><p className="copy-lg muted">One clear project lead keeps scope, feedback, and decisions connected from the first conversation to launch.</p></div></div></div></section>
      <section className="section section-dark motion-surface"><div className="container"><div className="section-head studio-capabilities-heading"><div><p className="eyebrow">Capabilities</p><h2>Modern tools.<br />Practical choices.</h2></div><p className="lead muted">We choose technology for maintainability, performance, and the people who will manage it—not because it is fashionable.</p></div><div className="stack-grid studio-capabilities-grid" data-stagger>{[["Design", "Figma, prototypes, design systems, motion direction, accessible UX."], ["Web", "TypeScript, React, Next.js, APIs, CMS platforms, testing and deployment."], ["Mobile", "Cross-platform products, responsive systems, native integrations and backend services."], ["Growth", "Technical SEO, analytics, content systems, campaigns and conversion testing."]].map(([title, text]) => <div className="stack-card" key={title}><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
      <section className="section section-purple big-cta"><div className="container big-cta-inner"><div><p className="eyebrow">Work with us</p><h2>A focused team for an important digital project.</h2><Link className="cta-pill" href="/contact"><span className="cta-pill-circle"><span>→&#xFE0E;</span></span><span className="cta-pill-text">Say hello</span></Link></div></div></section>
    </>
  );
}
